---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: transmission
  name: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      run: transmission
  template:
    metadata:
      labels:
        run: transmission
    spec:
      containers:    
      - name: transmission
        image: linuxserver/transmission
        env: []
        ports:
        - containerPort: 9091
          name: webui
          protocol: TCP
        - containerPort: 51413
          name: torrent-tcp
          protocol: TCP
        - containerPort: 51413
          name: torrent-udp
          protocol: UDP
        resources: {}
        livenessProbe:
          httpGet:
            path: /transmission/rpc
            port: webui
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /transmission/rpc
            port: webui
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:  []